import concreteImg1 from "../../assets/c1.png";
import concreteImg2 from "../../assets/c2.png";
import concreteImg3 from "../../assets/c3.png";
import concreteImg4 from "../../assets/c4.png";
import concreteImg5 from "../../assets/c5.png";
import concreteImg6 from "../../assets/c6.png";
import concreteImg7 from "../../assets/c7.png";
import concreteImg8 from "../../assets/c8.png";

export const concreteCasesData = [
  {
    id: 1,
    title1: "concrete_title_1",
    date: "Stern Online, 2001",
    contentTitle1: "what_happened",
    content1: "concrete_content_1",
    contentTitle2: "problem_title",
    content2: "concrete_content_1_2",
    contentTitle3: "prevent_title",
    list: ["concrete_content_1_3", "concrete_content_1_4"],
    img: concreteImg1,
  },
  {
    id: 2,
    title1: "concrete_title_2",
    date: "Spiegel Online, 2012",
    contentTitle1: "what_happened",
    content1: "concrete_content_2",
    contentTitle2: "problem_title",
    content2: "concrete_content_2_1",
    contentTitle3: "prevent_title",
    list: ["concrete_content_2_2"],
    img: concreteImg2,
  },
  {
    id: 3,
    title1: "concrete_title_3",
    date: "",
    contentTitle1: "what_happened",
    content1: "concrete_content_3",
    contentTitle2: "problem_title",
    content2: "concrete_content_3_1",
    contentTitle3: "prevent_title",
    list: ["concrete_content_3_2", "concrete_content_3_3"],
    img: concreteImg3,
  },
  {
    id: 4,
    title1: "concrete_title_4",
    date: "",
    contentTitle1: "what_happened",
    content1: "concrete_content_4",
    contentTitle2: "problem_title",
    content2: "concrete_content_4_1",
    contentTitle3: "prevent_title",
    list: ["concrete_content_4_2"],
    img: concreteImg4,
  },
  {
    id: 5,
    title1: "concrete_title_5",
    date: "",
    contentTitle1: "what_happened",
    content1: "concrete_content_5",
    contentTitle2: "problem_title",
    content2: "concrete_content_5_1",
    contentTitle3: "prevent_title",
    list: ["concrete_content_5_2", "concrete_content_5_3"],
    img: concreteImg5,
  },
  {
    id: 6,
    title1: "concrete_title_6",
    date: "welt.de, 2018",
    contentTitle1: "what_happened",
    content1: "concrete_content_6",
    contentTitle2: "problem_title",
    content2: "concrete_content_6_1",
    contentTitle3: "prevent_title",
    list: ["concrete_content_6_2", "concrete_content_6_3"],
    img: concreteImg6,
  },
  {
    id: 7,
    title1: "concrete_title_7",
    date: "",
    contentTitle1: "what_happened",
    content1: "concrete_content_7",
    contentTitle2: "problem_title",
    content2: "concrete_content_7_1",
    contentTitle3: "prevent_title",
    list: ["concrete_content_7_2", "concrete_content_7_3"],
    img: concreteImg7,
  },
  {
    id: 8,
    title1: "concrete_title_8",
    date: "",
    contentTitle1: "what_happened",
    content1: "concrete_content_8",
    contentTitle2: "problem_title",
    content2: "concrete_content_8_1",
    contentTitle3: "prevent_title",
    list: ["concrete_content_8_2", "concrete_content_8_3"],
    img: concreteImg8,
  },
];
